PharmacyMP/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PharmacyMP.Models;
using System.Security.Claims;

namespace PharmacyMP.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly PharmacyDbContext _context;

        public AuthorizationController(PharmacyDbContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(User user)
        {
            if (ModelState.IsValid)
            {
                user.RoleId = 2;
                _context.Users.Add(user);
                await _context.SaveChangesAsync();
                var userCart = new Cart();
                userCart.Id = user.Id;
                _context.Carts.Add(userCart);
                await _context.SaveChangesAsync();
                await Authorization(user.Login, user.Password);
                return RedirectToAction("Index", "Products");
            }
            else
            {
                return View(user);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Authorization(string login, string password)
        {
            if (string.IsNullOrEmpty(login) || string.IsNullOrEmpty(password))
            {
                return BadRequest("Email и/или пароль не установлены.");
            }

            var worker = await _context.Users.FirstOrDefaultAsync(w => w.Login == login && w.Password == password);
            if (worker == null)
            {
                return Unauthorized("Такого пользователя не найдено. Проверьте, правильно ли введены логин и пароль.");
            }

            // Получение должности пользователя из базы данных
            var jobtitle = await _context.Roles.FirstOrDefaultAsync(j => j.Id == worker.RoleId);
            if (jobtitle == null)
            {
                return NotFound("Должность не найдена.");
            }

            // Создание claims для аутентификации
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, worker.Login),
                new Claim(ClaimTypes.Role, jobtitle.Name),
                new Claim("Id", worker.Id.ToString(), ClaimValueTypes.Integer32)
                // Другие claims, если необходимо
            };

            var claimsIdentity = new ClaimsIdentity(claims, "Cookies");
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

            // Аутентификация пользователя
            if (HttpContext != null)
            {
                await  HttpContext.SignInAsync(claimsPrincipal);
            }

            if (HttpContext != null)
            {
            return RedirectToAction("Index", "Products");
            }

            return RedirectToAction("Index", "Products");
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Products");
        }
    }
}

PharmacyMP/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PharmacyMP.Models;

namespace Pharmacy.Controllers
{
    public class ProductsController : Controller
    {
        private readonly PharmacyDbContext _context;

        public ProductsController(PharmacyDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
              return _context.Products != null ? 
                          View(await _context.Products.ToListAsync()) :
                          Problem("Нет данных в таблице dbo.Products.");
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> AddToCart(int? id)
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id")?.Value;
            var cartItem = new CartItem();
            var cartProduct = await _context.CartItems.FirstOrDefaultAsync(ci => ci.ProductId == id && ci.CartId.ToString() == userId);
            

            if (cartProduct == null)
            {
                cartItem.CartId = Convert.ToInt32(userId);
                cartItem.ProductId = id;
                var prod = _context.Products.FirstOrDefault(c => c.Id == cartItem.ProductId);
                cartItem.Quantity = 1;
                cartItem.Price = prod.Price;
                _context.CartItems.Add(cartItem);
                prod.Quantity -= 1;
                _context.Update(prod);
            }
            else
            {
                var prod = _context.Products.FirstOrDefault(c => c.Id == cartProduct.ProductId);
                cartProduct.Quantity += 1;
                cartProduct.Price += prod.Price;
                _context.Update(cartProduct);
                prod.Quantity -= 1;
                _context.Update(prod);
            }
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> PutAway(int? id)
        {
            var item = await _context.CartItems.FirstOrDefaultAsync(c => c.Id == id);
            var prod = _context.Products.FirstOrDefault(p => p.Id == item.ProductId);

            if (item.Quantity > 1)
            {
                item.Quantity -= 1;
                item.Price -= prod.Price;
                _context.Update(item);
                prod.Quantity += 1;
                _context.Update(prod);
            }
            else
            {
                _context.CartItems.Remove(item);
                prod.Quantity += 1;
                _context.Update(prod);
            }
            await _context.SaveChangesAsync();

            return RedirectToAction("PersonalAccount", "Users");
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> BuyAllProducts()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id")?.Value;
            var user = await _context.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            var cartItems = await _context.CartItems
                .Where(c => c.CartId.ToString() == userId).
                Include(p => p.Product)
                .ToListAsync();

            if (cartItems != null)
            {
                _context.RemoveRange(cartItems);
            }
            else
            {
                return Problem("");
            }
            await _context.SaveChangesAsync();

            return RedirectToAction("PersonalAccount", "Users");
        }

        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,Quantity,Symptoms,IfPrescription")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Description,Quantity,Symptoms,IfPrescription")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'PharmacyDbContext.Products'  is null.");
            }


            var cartItems = await _context.CartItems.Where(m => m.ProductId == id).ToListAsync();
            if (cartItems != null)
            {
                _context.CartItems.RemoveRange(cartItems);
            }
            await _context.SaveChangesAsync();

            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }

        [HttpGet]
        public JsonResult GetProductNames(string term)
        {
            var productNames = _context.Products
                .Where(p => p.Name.Contains(term))
                .Select(p => p.Name)
                .ToList();

            return Json(productNames);
        }
    }
}

PharmacyMP/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pharmacy.ViewModels;
using PharmacyMP.Models;

namespace PharmacyMP.Controllers
{
    public class UsersController : Controller
    {
        private readonly PharmacyDbContext _context;

        public UsersController(PharmacyDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var pharmacyDbContext = _context.Users.Include(u => u.Role).OrderBy(u => u.Role.Name == "User");
            return View(await pharmacyDbContext.ToListAsync());
        }

        public async Task<IActionResult> PersonalAccount()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id")?.Value;
            var user = await _context.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            var cartItems = await _context.CartItems
                .Where(c => c.CartId.ToString() == userId).
                Include(p => p.Product)
                .ToListAsync();
            
            List<Product?> products = cartItems.Select(ci => ci.Product).ToList();

            var account = new AccountViewModel()
            {
                User = user!,
                Products = products!,
                CartItems = cartItems
            };
            return View(account);
        }

        // GET: Users/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Login,Password,RoleId,Name,Gender,Phone,Email")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                var userCart = new Cart();
                userCart.Id = user.Id;
                _context.Carts.Add(userCart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Login,Password,RoleId,Name,Gender,Phone,Email")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userCart = await _context.Carts.FindAsync(id);
            var cartItems = await _context.CartItems.Where(ci => ci.CartId == id).ToListAsync();
            if (userCart != null)
            {
                if (cartItems.Count != 0)
                {
                    foreach (var item in cartItems)
                    {
                        _context.CartItems.Remove(item);
                        await _context.SaveChangesAsync();
                    }
                }
                _context.Carts.Remove(userCart);
            }
            await _context.SaveChangesAsync();

            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

PharmacyMP/Views/Shared/Header.cshtml
@using System.Security.Claims;
<header>
    <ul>
        <li><a asp-controller="Products" asp-action="Index">Products</a></li>
        @if (User.FindFirst(ClaimTypes.Role)?.Value! == "Admin")
        {
            <li><a asp-controller="Users" asp-action="Index">Users</a></li>
        }
    </ul>

    @if (User.Identity.IsAuthenticated)
    {
        <form method="post">
            <button type="submit" asp-controller="Users" asp-action="PersonalAccount" asp-route-id="">
                Personal Account
            </button>
        </form>
        <form method="post">
            <button type="submit" asp-controller="Authorization" asp-action="Logout">
                Sign out
            </button>
        </form>
    }
    else
    {
        <form method="post">
            <button type="submit" asp-controller="Authorization" asp-action="Login">
                Sign In
            </button>
        </form>
        <form method="post">
            <button type="submit" asp-controller="Authorization" asp-action="SignUp" >
                Sign Up
            </button>
        </form>
    }
</header>

PharmacyMP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>Pharmacy</title>
    </head>
    <style>
    /* Общие стили */
    body {
        font-family: 'Arial', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f9;
        color: #333;
    }

    /* Стили для заголовка и навигации */
    header {
        background-color: #4CAF50;
        padding: 10px 0;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

        header ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
        }

            header ul li {
                margin: 0 15px;
            }

                header ul li a {
                    text-decoration: none;
                    color: white;
                    font-weight: bold;
                }

        header form {
            display: inline-block;
            margin-left: 10px;
        }

        header button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 8px 16px;
            margin: 0 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            border-radius: 4px;
        }

            header button:hover {
                background-color: #45a049;
            }

    /* Стили для таблицы продуктов */
    h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #333;
    }

    table {
        width: 90%;
        margin: 0 auto;
        border-collapse: collapse;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .createa {
            text-align: center;
        }

        table th, table td {
            padding: 12px 15px;
            border: 1px solid #ddd;
            text-align: left;
        }

        table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        table tr:hover {
            background-color: #f1f1f1;
        }

        a {
            color: #4CAF50;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease;
        }

            a:hover {
                color: #45a049;
            }

    /* Стили для кнопок */
    button {
        background-color: #4CAF50;
        color: white;
        border: none;
        padding: 10px 20px;
        margin: 10px 0;
        cursor: pointer;
        transition: background-color 0.3s ease;
        border-radius: 4px;
    }

        button:hover {
            background-color: #45a049;
        }

        button:disabled {
            background-color: #ccc;
            cursor: not-allowed;
        }

    input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        border: none;
        padding: 10px 20px;
        margin: 10px 0;
        cursor: pointer;
        transition: background-color 0.3s ease;
        border-radius: 4px;
    }

        input[type="submit"]:hover {
            background-color: #45a049;
        }

        input[type="submit"]:disabled {
            background-color: #ccc;
            cursor: not-allowed;
        }

    .specialform {
            margin-left: 10px;
        }

    .form-group {
        margin-bottom: 5px;
    }

    .differentstyle {
        margin-left: 0px;
        width: 100px;
    }
</style>
    <body>
        @await Html.PartialAsync("Header")
        @RenderBody()
    </body>
</html>